model_info:
  model_api_path: 'michiyasunaga/BioLinkBERT-base'
  base_model_name: 'cross_encoder_biolinkbert_base'
  base: biolinkbert_base
  num_labels: 2
  pretrained_on: pubmed_pmc_links
  batch_size: 8
  fine_tuned_on: