model_info:
  model_api_path: 'microsoft/deberta-v3-base'
  base_model_name: 'cross_encoder_deberta_base'
  base: deberta_base
  num_labels: 2
  pretrained_on: wikipedia_plus
  batch_size: 8
  fine_tuned_on: