model_info:
  model_api_path: 'microsoft/deberta-v3-small'
  base_model_name: 'cross_encoder_deberta_small'
  base: deberta_small
  num_labels: 2
  pretrained_on: wikipedia_plus
  batch_size: 16
  fine_tuned_on: