model_info:
  model_api_path: 'google/bert_uncased_L-4_H-512_A-8'
  base_model_name: 'cross_encoder_bert_small'
  base: bert_small
  num_labels: 2
  pretrained_on: wikipedia
  batch_size: 16
  fine_tuned_on: