model_info:
  model_api_path: 'microsoft/BiomedNLP-PubMedBERT-large-uncased-abstract'
  base_model_name: 'cross_encoder_pubmedbert_large'
  base: pubmedbert_large
  num_labels: 2
  pretrained_on: pubmed_abstracts
  batch_size: 8
  fine_tuned_on: