model_info:
  model_api_path: 'kamalkraj/bioelectra-base-discriminator-pubmed'
  base_model_name: 'cross_encoder_bioelectra'
  base: bioelectra
  num_labels: 2
  pretrained_on: pubmed_pmc
  batch_size: 8
  fine_tuned_on: