model_info:
  model_api_path: 'microsoft/biogpt'
  base_model_name: 'cross_encoder_biogpt'
  base: biogpt_seq_classification
  num_labels: 2
  pretrained_on: pubmed_abstract
  batch_size: 4
  fine_tuned_on: