model_info:
  model_api_path: 'google/electra-small-discriminator'
  base_model_name: 'cross_encoder_electra_small'
  base: electra_small
  num_labels: 2
  pretrained_on: wikipedia_plus
  batch_size: 16
  fine_tuned_on: