model_info:
  model_api_path: 'distilroberta-base'
  base_model_name: 'cross_encoder_distilroberta'
  base: distilroberta
  num_labels: 2
  pretrained_on: open_web_text
  batch_size: 16
  fine_tuned_on: